# Generated by Django 4.1.7 on 2023-07-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='core.lesson'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='core.quiz'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lesson'),
        ),
    ]
